### ISSUE TITLE
Epic: Create value analysis API

### ISSUE THREAD

**Issue by adamfowleruk** [vmware/herald-for-cpp#29]
Initial API creation work to support user stories around the mid-level API. User stories in other issues.

Required features:-

- [ ] Representation of a Typed Value that has been produced
- [ ] Representation of a fixed maximum windowed and filtered aggregation algorithm
- [ ] Generic re-usable filters (min/max) 
- [ ] Generic re-usable aggregators (mean, median, mode, variance, sd, min, max)
- [ ] Ability to produce and consume values - Single produced value for now (i.e. we don't go back and 'fix' values that have already been produced)
- [ ] Sink to save a produced value (E.g. results in to a CSV file, or metadata for upload)
- [ ] Source to produce values (E.g. live BLE device, or previous results in a CSV file)
